version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
    - 0.16.0
  - dependency-name: orjson
    versions:
    - 3.4.7
    - 3.4.8
    - 3.5.0
    - 3.5.1
